STRUCTURE:
  model_name: evissgnet
  width: 12
  block_residual: True
  block_reps: 2
  use_coords: True

DATA:
  input_channel: 4
  root: /home/yoon/jk/EV-UAV/EV-UAV/dataset
  whole_t: 4000 #ms 8000 -> 4000
  res: [346,260]

TRAIN:
  epochs: 50
  batch_size: 1
  train_workers: 2 # 8->2
  optim: Adam # Adam or SGD
  lr: 0.001
  k: 3
  t: 5
  max_events_num : 200000 # 700000->200000
  model_save_root:  /home/yoon/jk/EV-UAV/EV-UAV/save_model

TEST:
  vis: False
  eval: True
  roc: True  # Very time-consuming, do not open unless necessary
  pd_detT: 50
  correct_thresh: 0.0001
  save: True
  model_path: /home/yoon/jk/EV-UAV/EV-UAV/save_model/best_iou.pt



